### ISSUE TITLE
editor keeps blinking and won't respond

### ISSUE THREAD

**Issue by Sid009hey** [Mani4D46/strawberry-editor#3]
the start screen shows up but all the characters and text start blinking including the pixel art, and the editor then stops responding.. running python 3.8 on kitty terminal, pop_os 20.04 LTS..

**Comment by manifarizi** [comment]
that could means your terminal (in this case kitty) screen size has been changed, Is that true?

**Comment by manifarizi** [comment]
if yes that's a known bug and I try to fix it but I always forgot

**Comment by Sid009hey** [comment]
no the screensize hasn't been changed.. but i do have remember window size turned on so it maybe a bit bigger than the initial window width..

**Comment by Mani4D46** [comment]
that's weird have you tried the latest version?

**Comment by Sid009hey** [comment]
yeah i have

**Comment by Mani4D46** [comment]
idk I don't really update it anymore
